# Generated by Django 3.1.7 on 2021-03-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
